// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17507
#define LPobjName		lp.vim
//#define LPobjStarter		1							// Comment out for Pro Bundles
#define LPobjMajorRev		1
#define LPobjMinorRev		2							// NEW: separate Minor revision and
#define LPobjBugFix			0							//		bug fix data
#define LPobjStage			finalStage
#define LPobjStageBuild		1
#define LPobjRegion			0							// US
#define LPobjVersStr		1.2fc1
#define LPobjCRYears		2001-08
#define LPobjMax3Category	Control					// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	Control					// Category starting at Max 4
#define LPobjDescription	Interval mutation of numeric values

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
