// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17559
#define LPobjName		lp.ccc
//#define LPobjStarter		1								// Comment out for Pro Bundles
#define LPobjMajorRev		1
#define LPobjMinorRev		2
#define LPobjBugFix			0
#define LPobjStage			finalStage
#define LPobjStageBuild		1
#define LPobjRegion			0								// US
#define LPobjVersStr		1.2fc1
#define LPobjCRYears		2001-08
#define LPobjMax3Category	Arith/Logic/Bitwise			// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	Math							// Category starting at Max 4
#define LPobjDescription	Generate chaotic sequences with 1/f distribution 		\

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
