// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17549
#define LPobjName		lp.poppy~
#define LPobjStarter		1								// Comment out for Pro Bundles
#define LPobjMajorRev		1
#define LPobjMinorRev		3
#define LPobjBugFix			0
#define LPobjStage			finalStage
#define LPobjStageBuild		1
#define LPobjRegion			0								// US
#define LPobjVersStr		1.3fc1
#define LPobjCRYears		2001-08
#define LPobjMax3Category	MSP							// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	MSP Synthesis					// Category starting at Max 4
#define LPobjDescription	Population growth model as signal

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
