// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17490
#define LPobjName		lp.epoisse~
#define LPobjStarter		1							// Comment out for Pro Bundles
#define LPobjMajorRev		1							// 1-99	(decimal)
#define LPobjMinorRev		0							// 0-9	(decimal)
#define LPobjBugFix			1							// 0-9	(deicmal)
#define LPobjStage			alphaStage					// Standard Apple stage
#define LPobjStageBuild		2							// 1-255 (0 for Golden Master only)
#define LPobjRegion			0							// US
#define LPobjVersStr		1.0.1a2
#define LPobjCRYears		2001-09
#define LPobjMax3Category	MSP						// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	MSP Synthesis				// Category starting at Max 4
#define LPobjDescription	Pitched noise

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
