// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17573
#define LPobjName		lp.gruyère~
//#define LPobjStarter		1							// Comment out for Pro Bundles
#define LPobjMajorRev		1							// 1-99	(decimal)
#define LPobjMinorRev		1							// 0-9	(decimal)
#define LPobjBugFix			0							// 0-9	(deicmal)
#define LPobjStage			betaStage					// Standard Apple stage
#define LPobjStageBuild		1							// 1-255 (0 for Golden Master only)
#define LPobjRegion			0							// US
#define LPobjVersStr		1.0b1
#define LPobjCRYears		2001-04
#define LPobjMax3Category	MSP						// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	MSP Synthesis				// Category starting at Max 4
#define LPobjDescription	Uniform Markov noise

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
