// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17570
#define LPobjName		lp.ksks~
#define LPobjStarter		1							// Comment out for Pro Bundles
#define LPobjMajorRev		0							// 1-99	(decimal)
#define LPobjMinorRev		0							// 0-9	(decimal)
#define LPobjBugFix			0							// 0-9	(deicmal)
#define LPobjStage			alphaStage					// Standard Apple stage
#define LPobjStageBuild		1							// 1-255 (0 for Golden Master only)
#define LPobjRegion			0							// US
#define LPobjVersStr		1.0a1
#define LPobjCRYears		2004
#define LPobjMax3Category	MSP						// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	MSP Synthesis				// Category starting at Max 4
#define LPobjDescription	Plucked noise

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
