// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17540
#define LPobjName		lp.pvvv~
#define LPobjStarter		1							// Comment out for Pro Bundles
#define LPobjMajorRev		1							// 1-99	(decimal)
#define LPobjMinorRev		3							// 0-9	(decimal)
#define LPobjBugFix			0							// 0-9	(decimal)
#define LPobjStage			finalStage					// Standard Apple stage
#define LPobjStageBuild		1							// 1-255 (0 for Golden Master only)
#define LPobjRegion			0							// US
#define LPobjVersStr		1.3fc1
#define LPobjCRYears		2001-08
#define LPobjMax3Category	MSP						// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	MSP Synthesis				// Category starting at Max 4
#define LPobjDescription	Colored noise with variable Hurst exponent

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
