// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17502
#define LPobjName		lp.coshy
//#define LPobjStarter		1							// Comment out for Pro Bundles
#define LPobjMajorRev		2							// 1-99 (decimal)
#define LPobjMinorRev		1							// 1-9	(decimal)
#define LPobjBugFix			0							// 1-9	(decimal)
#define LPobjStage			finalStage					// Apple standard stage #defines
#define LPobjStageBuild		1							// 1-255 (0 for Golden Master only)
#define LPobjRegion			0							// US
#define LPobjVersStr		2.1fc1
#define LPobjCRYears		2001-08
#define LPobjMax3Category	Arith/Logic/Bitwise		// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	Math						// Category starting at Max 4
#define LPobjDescription	Generate random numbers from a Cauchy distribution

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
