// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17581
#define LPobjName		lp.argus
#define LPobjStarter		1							// Comment out for Pro Bundles
#define LPobjMajorRev		1
#define LPobjMinorRev		2
#define LPobjBugFix			0
#define LPobjStage			alphaStage
#define LPobjStageBuild		1
#define LPobjRegion			0							// US
#define LPobjVersStr		1.2a1
#define LPobjCRYears		2006-08
#define LPobjMax3Category	System				// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	System				// Category starting at Max 4
#define LPobjDescription	Enforce standard window behavior in Max Patcher windows

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
