// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17588
#define LPobjName		lp.crabelms
#define LPobjStarter		1								// Comment out for Pro Bundles
#define LPobjMajorRev		1
#define LPobjMinorRev		1
#define LPobjBugFix			0
#define LPobjStage			finalStage
#define LPobjStageBuild		1
#define LPobjRegion			0								// US
#define LPobjVersStr		1.1fc1
#define LPobjCRYears		2006-08
#define LPobjMax3Category	Data						// Category for Max 2.2 - 3.6x, N/A
#define LPobjMax4Category	Data						// Category starting at Max 4
#define LPobjDescription	Scramble a list

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
