// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17515
#define LPobjName		lp.i
//#define LPobjStarter		1							// Comment out for Pro Bundles
#define LPobjMajorRev		1
#define LPobjMinorRev		2
#define LPobjBugFix			0
#define LPobjStage			finalStage
#define LPobjStageBuild		1
#define LPobjRegion			0							// US
#define LPobjVersStr		1.2fc1
#define LPobjCRYears		2001-08
#define LPobjMax3Category	Messages					// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	Messages					// Category starting at Max 4
#define LPobjDescription	Text of I Ching oracles
#define LPobjDescription	Text of I Ching oracles

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
