// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17526
#define LPobjName		lp.kg
//#define LPobjStarter		1								// Comment out for Pro Bundles
#define LPobjMajorRev		1
#define LPobjMinorRev		2
#define LPobjBugFix			0
#define LPobjStage			finalStage
#define LPobjStageBuild		0x00
#define LPobjRegion			0								// US
#define LPobjVersStr		1.2fc1
#define LPobjCRYears		2001-08
#define LPobjMax3Category	Arith/Logic/Bitwise		// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	Math						// Category starting at Max 4
#define LPobjDescription	Map I Ching values to other ranges

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
