// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17563
#define LPobjName		lp.logos
//#define LPobjStarter		1							// Comment out for Pro Bundles
#define LPobjMajorRev		2
#define LPobjMinorRev		1
#define LPobjBugFix			0
#define LPobjStage			finalStage
#define LPobjStageBuild		1
#define LPobjRegion			0							// US
#define LPobjVersStr		2.1fc1
#define LPobjCRYears		2003-08
#define LPobjMax3Category	Arith/Logic/Bitwise		// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	Math						// Category starting at Max 4
#define LPobjDescription	Quotient, remainder, and modulo

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
