// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17580
#define LPobjName		lp.mrsnorris
#define LPobjStarter		1							// Comment out for Pro Bundles
#define LPobjMajorRev		1
#define LPobjMinorRev		1
#define LPobjBugFix			0
#define LPobjStage			finalStage
#define LPobjStageBuild		1
#define LPobjRegion			0							// US
#define LPobjVersStr		1.1fc1
#define LPobjCRYears		2006-08
#define LPobjMax3Category	System				// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	System				// Category starting at Max 4
#define LPobjDescription	Open patcher files or bring open windows to front

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
