// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjStarter		1								// Comment out for Pro Bundles
#define LPobjStage			finalStage
#define LPobjStageBuild		0x00
#define LPobjVersStr		1.1.2
#define LPobjCRYears		2003-04

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
