// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17497
#define LPobjName		lp.stacey
#define LPobjStarter		1								// Comment out for Pro Bundles
#define LPobjMajorRev		2
#define LPobjMinorRev		1
#define LPobjBugFix			1
#define LPobjStage			finalStage
#define LPobjStageBuild		0
#define LPobjRegion			0								// US
#define LPobjVersStr		2.1.1
#define LPobjCRYears		2003-09
#define LPobjMax3Category	Arith/Logic/Bitwise		// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	Math						// Category starting at Max 4
#define LPobjDescription	Collect statistics

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
