// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjStage			betaStage					// Apple standard stage #defines
#define LPobjStageBuild		1							// 1-255 (0 for Golden Master only)
#define LPobjVersStr		1.0b1
#define LPobjCRYears		2006

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
