// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17593
#define LPobjName		lbj.bixmap
#define LPobjLBJ			1
#define LPobjMajorRev		1
#define LPobjMinorRev		0
#define LPobjBugFix			0
#define LPobjStage			betaStage
#define LPobjStageBuild		2
#define LPobjRegion			0							// US
#define LPobjVersStr		1.0b2
#define LPobjCRYears		2003-08
#define LPobjMax3Category								// Not available in Max 2.2 - 3.6x
#define LPobjMax4Category	Jitter Data				// Category starting at Max 4
#define LPobjDescription	BIX input-to-output mapping

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
