// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17576
	#define LPobjName		lbj.bixpack
#define LPobjLBJ			1
#define LPobjMajorRev		1
#define LPobjMinorRev		2
#define LPobjBugFix			0
#define LPobjStage			finalStage
#define LPobjStageBuild		1
#define LPobjRegion			0							// US
#define LPobjVersStr		1.2fc1
#define LPobjCRYears		2003-13
#define LPobjMax3Category								// Not available in Max 2.2 - 3.6x
#define LPobjMax4Category	Jitter Analysis			// Category starting at Max 4
#define LPobjDescription	Pack Jitter data for UDP network transport

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
