// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17583
#define LPobjName		lbj.pfishie
#define LPobjLBJ			1
#define LPobjMajorRev		0							// 1-99 (decimal)
#define LPobjMinorRev		0							// 1-9	(decimal)
#define LPobjBugFix			0							// 1-9	(decimal)
#define LPobjStage			finalStage				// Apple standard stage #defines
#define LPobjStageBuild		1							// 1-255 (0 for Golden Master only)
#define LPobjRegion			0							// US
#define LPobjVersStr		1.0fc1
#define LPobjCRYears		2006
#define LPobjMax3Category								// Category for Max 2.2 - 3.6x
#define LPobjMax4Category	Jitter Generators			// Category starting at Max 4
#define LPobjDescription	Generate Gaussian noise

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
