// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17573
#define LPobjName		lbj.stacey
#define LPobjLBJ			1
#define LPobjMajorRev		1
#define LPobjMinorRev		1
#define LPobjBugFix			0
#define LPobjStage			finalStage
#define LPobjStageBuild		1
#define LPobjRegion			0							// US
#define LPobjVersStr		1.1fc1
#define LPobjCRYears		2005-06
#define LPobjMax3Category								// Not available in Max 2.2 - 3.6x
#define LPobjMax4Category	Jitter Analysis			// Category starting at Max 4
#define LPobjDescription	Collect frame statistics for Jitter

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
