// This file is automatically generated
// There is no point in editing manually--edit the .r file instead

#define LPobjID			17575
	#define LPobjName		lbj.bixunpack
#define LPobjLBJ			1
#define LPobjMajorRev		1
#define LPobjMinorRev		1
#define LPobjBugFix			1
#define LPobjStage			finalStage
#define LPobjStageBuild		1
#define LPobjRegion			0							// US
#define LPobjVersStr		1.1.1
#define LPobjCRYears		2003-13
#define LPobjMax3Category								// Not available in Max 2.2 - 3.6x
#define LPobjMax4Category	Jitter Data				// Category starting at Max 4
#define LPobjDescription	Unpack Jitter data from incoming UDP stream

#ifdef LPobjStarter
	#define LPobjBundle All Bundles
#else
	#define LPobjBundle Pro Bundle
#endif
